`use strict`;

// importing another js file contents

// html elemnts
// input box
const guessBox = document.querySelector(`.guess`);

// check btn
const checkButton = document.querySelector(`.check`);

// message
const message = document.querySelector(`.message`);

// score
const attempt = document.querySelector(`.attempt`);

// highscore
const highscore = document.querySelector(`.highscore`);

// secret number
const num = document.querySelector(`.number`);

// body
const body = document.querySelector(`body`);

// level buttons
const level = document.querySelectorAll(`.btn.level`);

let tempHighscore = 0;

// to let the user know the level is selected or not
let levelSelected = false;

// store the number generated by system
let secretNum;

// to set difficulty level based on user selection
const setDifficulty = (lvl) => {
  // to change the difficulty
  if (lvl == `easy`) {
    levelSelected = true;
    guessBox.value = ``;
    // attempt
    score.textContent = 5;
    // hint message
    message.textContent = `Guess a number between 1 and 20`;
    // to change the difficulty to easy
    return 20;
  } else if (lvl == `medium`) {
    levelSelected = true;
    guessBox.value = ``;
    // attempts
    score.textContent = 7;
    // hint message
    message.textContent = `Guess a number between 1 and 50`;
    // to change the difficulty to medium
    return 50;
  } else if (lvl == `hard`) {
    levelSelected = true;
    guessBox.value = ``;
    // attempts
    score.textContent = 10;
    // hint message
    message.textContent = `Guess a number between 1 and 100`;
    // to change the difficulty to hard
    return 100;
  }
};

// to update the select by user level
const lvlEvent = () => {
  // to target the buttons difficulty atrribute
  level.forEach((level) => {
    // event listener to select the level get difficulty value
    level.addEventListener("click", (event) => {
      const levels = event.target.getAttribute("difficulty");
      // call the setDifficulty function and storing its return value
      let value = setDifficulty(levels);
      // generate a random number based on the value
      secretNum = Math.floor(Math.random() * value) + 1;
    });
  });
};

lvlEvent();

// store the system generated number
let newSecNum = secretNum;

// check the user entered number 
const check = () => {
  // level is not selected
  if (levelSelected == false) {
    message.textContent = `😒Please select a level`;
  } else {
    // level is selected
    // user does not enter the number
    if (!guessBox.value) {
      message.textContent = `😕Please guess a number`;
    } else {
      // game logic

      //user entered number is too high
      if (guessBox.value > secretNum) {
        message.textContent = `Too High`;
        // attempts deduction
        if (attempt.textContent > 0) {
          attempt.textContent = score.textContent - 1;
        }
        if (attempt.textContent == 0) {
          message.textContent = `😢You loose the game`;
          body.style.backgroundColor = `#f95959`;
          again.style.color = `#f95959`;
          checkButton.style.color = `#f95959`;
          num.style.color = `#f95959`;
          again.style.display = `block`;
          again.disabled = false;
        }
      }
      //user entered number is too low
      if (guessBox.value < secretNum) {
        message.textContent = `Too Low`;
        if (attempt.textContent > 0) {
          attempt.textContent = attempt.textContent - 1;
        }
        if (attempt.textContent == 0) {
          message.textContent = `😢You loose the game`;
          body.style.backgroundColor = `#f95959`;
          again.style.color = `#f95959`;
          checkButton.style.color = `#f95959`;
          level.style.color = `#f95959`;
          num.style.color = `#f95959`;
          again.style.display = `block`;
        }
      }
      //user entered number is correct
      if (guessBox.value == secretNum) {
        message.textContent = `🎉Correct Guess`;
        body.style.backgroundColor = `#60b347`;
        num.textContent = secretNum;
        highscore.textContent = +5;
        tempHighscore = highattempt.textContent;
        again.style.display = `block`;
      }
    }
  }
};

checkButton.addEventListener(`click`, check);

// again btn
const again = document.querySelector(`.btn.again`);

// restart the game
const playAgain = () => {
  guessBox.value = ``;
  message.textContent = `Choose a level`;
  body.style.backgroundColor = `#a9bff6`;
  num.textContent = `?`;
  again.style.display = `none`;
  levelSelected = false;
  again.style.color = `#a9bff6`;
  num.style.color = `#a9bff6`;
  checkButton.style.color = `#a9bff6`;
  highscore.textContent = tempHighscore;
  s;
};

again.addEventListener(`click`, playAgain);

// rules
// btn
const rule = document.querySelector(`.rules-btn`);
// rule window
const rulesBook = document.querySelector(`.rule-book`);
// close btn
const close = document.querySelector(`.close`);

const showRulesBook = false;

const showRules = () => {
  rulesBook.style.display = `block`;
};

const closeRules = () => {
  rulesBook.style.display = `none`;
};

const closeTxt = () => {
  close.textContent = `x`;
};

const closeText = () => {
  close.textContent = `close`;
};

// show rules
rule.addEventListener(`click`, showRules);

// close rules
close.addEventListener(`click`, closeRules);

// close text
close.addEventListener(`mouseover`, closeTxt);

// close text
close.addEventListener(`mouseout`, closeText);
